name: CI/CD Duplicate Removal Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run duplicate removal script
        run: |
          python scripts/remove_duplicates.py

      - name: Commit processed dataset
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/processed_dataset.csv
          git commit -m "Add processed_dataset.csv"
          git push

      - name: List data folder
        run: |
          ls -l data/






